name: 'ci-develop-main'

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run tests & build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: sadajo_fe/node_modules
          key: npm-packages-${{ hashFiles('**/sadajo_fe/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd sadajo_fe
          npm install

      - name: Run Build
        run: |
          cd sadajo_fe
          npm run build

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # ✅ main 브랜치에서만 배포 실행

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Netlify
        run: |
          cd sadajo_fe
          npx netlify-cli deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

#test for ci/cd